''7-base_geometry.py'' module
=============================================

Using BaseGeometry class
---------------------------------------------

***Tests on integer_validator function***
---------------------------------------------

Import module
    >>> BG = __import__("7-base_geometry").BaseGeometry

Check Base cases
    >>> obj = BG()
    >>> obj.integer_validator("Name1", 12)
    >>> obj.integer_validator("Name2", 41234)
    >>> obj.integer_validator("", 41234)

Check Raise cases
    >>> obj.integer_validator("ARG","XO")
    Traceback (most recent call last):
    TypeError: ARG must be an integer

    >>> obj.integer_validator("Boyka", 0)
    Traceback (most recent call last):
    ValueError: Boyka must be greater than 0

    >>> obj.integer_validator("Boyka", -14213)
    Traceback (most recent call last):
    ValueError: Boyka must be greater than 0

    >>> obj.integer_validator("", -14213)
    Traceback (most recent call last):
    ValueError:  must be greater than 0

Missing required arguments
    >>> obj.integer_validator("ARG")
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    >>> obj.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

check area function
    >>> obj.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

    >>> obj.area("GEOMETRY")
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 2 were given

    >>> obj.area("GEOMETRY", 1)
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 3 were given

    >>> obj.area("GEOMETRY", 1, 8)
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 4 were given

Check some extra cases
    >>> obj.integer_validator("XYZ", True)
    Traceback (most recent call last):
    TypeError: XYZ must be an integer

    >>> obj.integer_validator("XYZ", [1, 2])
    Traceback (most recent call last):
    TypeError: XYZ must be an integer

    >>> obj.integer_validator("XYZ", {5, 6})
    Traceback (most recent call last):
    TypeError: XYZ must be an integer

    >>> obj.integer_validator("XYZ", None)
    Traceback (most recent call last):
    TypeError: XYZ must be an integer

    >>> obj.integer_validator("XYZ", (4,6,8))
    Traceback (most recent call last):
    TypeError: XYZ must be an integer
